name: Build docker images with kaniko

on:
  push:
    branches: [ main ]
    tags:
      - '*'

jobs:
  deploy-ghcr:
    uses: liofal/action/workflows/build_and_deploy.yml
    with:
      registry: ghcr.io
      username: ${{ github.actor }}
      password: ${{ secrets.GITHUB_TOKEN }}
      images: ghcr.io/${{ github.repository }}

  deploy-dockerio:
    uses: liofal/action/workflows/build_and_deploy.yml
    with:
      registry: docker.io
      username: ${{ secrets.DOCKER_USERNAME }}
      password: ${{ secrets.DOCKER_TOKEN }}
      images: docker.io/${{ github.repository }}